In [3]:
import os
import numpy as np
import pandas as pd

# เส้นทางไปยังโฟลเดอร์ (แทนที่ 'username' ด้วยชื่อผู้ใช้ของคุณ)
path = "/Users/natthawutchungam/Documents"

# ตรวจสอบว่ามีโฟลเดอร์นี้หรือไม่ ถ้าไม่มีจะสร้างขึ้น
if not os.path.exists(path):
    os.makedirs(path)

# สร้างไฟล์ b1.in และเขียนข้อมูล Sudoku ลงไป ถ้าไฟล์ยังไม่มี
file_path = os.path.join(path, "b1.in")
sudoku_data = """0 2 9 7 6 3 8 0 1
3 0 8 0 1 0 6 0 0
5 6 1 9 0 0 0 0 3
0 0 0 6 0 2 3 0 5
6 0 0 0 4 0 0 0 8
2 0 0 8 3 1 4 0 0
8 0 2 1 0 0 0 6 4
0 4 5 0 0 6 0 0 0
0 9 0 2 0 0 0 0 0
"""

# เขียนข้อมูลลงในไฟล์ b1.in ถ้าไฟล์ไม่มี
if not os.path.exists(file_path):
    with open(file_path, "w") as file:
        file.write(sudoku_data)
    print(f"สร้างไฟล์ {file_path} สำเร็จ")

# อ่านข้อมูล Sudoku จากไฟล์
sdk_board = pd.read_csv(file_path, delimiter=' ', header=None)
sudoku_board = sdk_board.to_numpy()

print("บอร์ด Sudoku ก่อนแก้ไข:")
print(sudoku_board)

# ฟังก์ชันสำหรับหาช่องว่าง (เลข 0) ในบอร์ด
def get0in15(board):
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                return i, j
    return None

# ฟังก์ชันสำหรับตรวจสอบว่าตัวเลขใส่ได้หรือไม่
def isValid(board, row, col, num):
    for i in range(9):
        if board[row][i] == num or board[i][col] == num:
            return False
    
    s_row, s_col = 3 * (row // 3), 3 * (col // 3)
    for i in range(3):
        for j in range(3):
            if board[s_row + i][s_col + j] == num:
                return False
    
    return True

# ฟังก์ชันสำหรับแก้ปัญหา Sudoku โดยใช้ Backtracking
def solve16(board):
    cell = get0in15(board)
    if cell is None:
        return True
    row, col = cell
    for num in range(1, 10):
        if isValid(board, row, col, num):
            board[row][col] = num
            if solve16(board):
                return True
            board[row][col] = 0
    return False

# เรียกใช้ฟังก์ชันแก้ปัญหา Sudoku
if solve16(sudoku_board):
    print("บอร์ด Sudoku หลังแก้ไขสำเร็จ:")
    print(sudoku_board)
else:
    print("ไม่สามารถแก้ปัญหา Sudoku ได้")


บอร์ด Sudoku ก่อนแก้ไข:
[[0 2 9 7 6 3 8 0 1]
 [3 0 8 0 1 0 6 0 0]
 [5 6 1 9 0 0 0 0 3]
 [0 0 0 6 0 2 3 0 5]
 [6 0 0 0 4 0 0 0 8]
 [2 0 0 8 3 1 4 0 0]
 [8 0 2 1 0 0 0 6 4]
 [0 4 5 0 0 6 0 0 0]
 [0 9 0 2 0 0 0 0 0]]
บอร์ด Sudoku หลังแก้ไขสำเร็จ:
[[4 2 9 7 6 3 8 5 1]
 [3 7 8 4 1 5 6 2 9]
 [5 6 1 9 2 8 7 4 3]
 [9 8 4 6 7 2 3 1 5]
 [6 1 3 5 4 9 2 7 8]
 [2 5 7 8 3 1 4 9 6]
 [8 3 2 1 5 7 9 6 4]
 [7 4 5 3 9 6 1 8 2]
 [1 9 6 2 8 4 5 3 7]]
